{% set name = "jinxed" %}
{% set version = "2.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e755b831faa2443d44fb4ce7c0202eb9c3ed39bd5bf1193365888f4f6092b54

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - ansicon  # [win]
    - python

test:
  source_files:
    - tests
    - terminals.toml
  imports:
    - jinxed
    - jinxed.terminfo
  commands:
    - pip check
    - python -m pytest -vv tests
  requires:
    - pip
    - pytest
    - ncurses  # [not win]

about:
  home: https://pypi.org/project/jinxed
  summary: Jinxed Terminal Library
  description: |
    Jinxed is an implementation of a subset of the Python curses library. It provides pure Python implementations of
    terminfo functions such as tigetstr() and tparm() as well as convenience methods for working with Windows terminals.
  license_family: OTHER
  license: MPL-2.0
  license_file: LICENSE
  doc_url: https://jinxed.readthedocs.io
  dev_url: https://github.com/Rockhopper-Technologies/jinxed

extra:
  recipe-maintainers:
    - hadim
    - mattip
