{% set name = "jinxed" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d8f1731f134e9e6b04d95095845ae6c10eb15cb223a5f0cabdea87d4a279c305

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - ansicon  # [win]
    - python

test:
  imports:
    - jinxed
    - jinxed.terminfo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/jinxed/
  summary: Jinxed Terminal Library
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
