{% set name = "jinxed" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1593124b18a41b7a3da3b078471442e51dbad3d77b4d4f2b0c26ab6f7d660dbf

build:
  number: 0
  Skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - ansicon  # [win]
    - python

test:
  source_files:
    - tests
  imports:
    - jinxed
    - jinxed.terminfo
  commands:
    - pip check
    # skipping test_tparm.py as not comatible with  ncurses >= 6.4
    - pytest -k "not test_tparm.py" -vv
  requires:
    - pip
    - pytest
    - ncurses  # [not win]

about:
  home: https://pypi.org/project/jinxed/
  summary: Jinxed Terminal Library
  description: |
    Jinxed is an implementation of a subset of the Python curses library. It provides pure Python implementations of
    terminfo functions such as tigetstr() and tparm() as well as convenience methods for working with Windows terminals.
  license_family: OTHER
  license: MPL-2.0
  license_file: LICENSE
  doc_url: https://jinxed.readthedocs.io/
  dev_url: https://github.com/Rockhopper-Technologies/jinxed/

extra:
  recipe-maintainers:
    - hadim
    - mattip
